<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Colissimo\\Vendor\\setasign\\Fpdi\\' => array($vendorDir . '/setasign/fpdi/src'),
    'Colissimo\\' => array($baseDir . '/src'),
);
