<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit1ee9c1c9cba57d9c04895fc286b7b6de
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Colissimo\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Colissimo\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit1ee9c1c9cba57d9c04895fc286b7b6de', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Colissimo\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit1ee9c1c9cba57d9c04895fc286b7b6de', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Colissimo\Vendor\Composer\Autoload\ComposerStaticInit1ee9c1c9cba57d9c04895fc286b7b6de::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
