<?php
// phpcs:disable WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound -- Template partial included within Helper::renderPartial(); its variables are local to the include scope, not true globals.
defined('ABSPATH') || die('Restricted Access');
?>
<tr valign="top">
	<th scope="row" class="titledesc">
		<label><?php echo esc_html($args['title']); ?></label>
	</th>
	<td class="forminp forminp-<?php echo esc_attr($args['type']); ?>">
		<p class="description" id="lpc_qz_certificate_status">
            <?php
            echo $args['isConfigured']
                ? esc_html($args['certificateInfo'])
                : esc_html__('No certificate yet: QZ Tray asks the operator to allow every single print.', 'colissimo-shipping-methods-for-woocommerce');
            ?>
		</p>
		<p>
			<button
					type="button"
					class="button button-primary"
					id="lpc_qz_generate_button"
					data-url="<?php echo esc_url($args['generateUrl']); ?>">
                <?php
                echo $args['isConfigured']
                    ? esc_html__('Generate a new certificate', 'colissimo-shipping-methods-for-woocommerce')
                    : esc_html__('Generate the certificate', 'colissimo-shipping-methods-for-woocommerce');
                ?>
			</button>
			<button
					type="button"
					class="button"
					id="lpc_qz_download_button"
                <?php disabled(!$args['isConfigured']); ?>>
                <?php esc_html_e('Download certificate', 'colissimo-shipping-methods-for-woocommerce'); ?>
			</button>
		</p>
        <?php if (!empty($args['desc'])) : ?>
			<p class="description"><?php echo esc_html($args['desc']); ?></p>
        <?php endif; ?>
		<p>
			<a href="#" id="lpc_qz_import_toggle" class="description">
                <?php esc_html_e('I already have QZ Tray files (commercial licence or certificate generated by QZ Tray)', 'colissimo-shipping-methods-for-woocommerce'); ?>
			</a>
		</p>
	</td>
</tr>
